name: appcesible
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  # table_calendar: ^3.0.9
  flutter_screenutil:
  responsive_builder:
  shared_preferences: ^2.2.2
  fluttertoast: ^8.0.7
  path_provider: ^2.0.2
  path: ^1.8.0
  image_picker: ^1.0.4
  pointycastle: ^3.7.3
  asn1lib: ^1.5.0
  crypton: ^2.2.1
  video_player: ^2.8.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/